export const navigationIcons: Record<string, string> = {
  MANEUVER_UNSPECIFIED: 'help-circle-outline',
  TURN_SLIGHT_LEFT: 'arrow-forward-circle-outline',
  TURN_SHARP_LEFT: 'arrow-back-circle-outline',
  UTURN_LEFT: 'return-up-back-outline',
  TURN_LEFT: 'arrow-back-outline',
  TURN_SLIGHT_RIGHT: 'arrow-forward-circle-outline',
  TURN_SHARP_RIGHT: 'arrow-forward-circle-outline',
  UTURN_RIGHT: 'return-down-back-outline',
  TURN_RIGHT: 'arrow-forward-outline',
  STRAIGHT: 'arrow-up-outline',
  RAMP_LEFT: 'exit-outline',
  RAMP_RIGHT: 'enter-outline',
  MERGE: 'git-merge-outline',
  FORK_LEFT: 'git-branch-outline',
  FORK_RIGHT: 'git-branch-outline',
  FERRY: 'boat-outline',
  FERRY_TRAIN: 'train-outline',
  ROUNDABOUT_LEFT: 'repeat-outline',
  ROUNDABOUT_RIGHT: 'repeat-outline',
  NAME_CHANGE: 'swap-horizontal-outline',
};
